# Generated by Django 4.2 on 2024-12-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('javascript', 'javascript')], max_length=50, null=True),
        ),
    ]
